version: '3.8'

services:
  employees-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/user/current"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
